
// ══════════════════════════════════════════════════════════════════════════════
//  Niveaux de permission par commande
//  0 / absent = tout le monde   1 = membre basique   2 = staff débutant
//  3 = modérateur junior        4 = modérateur        5 = administrateur
//  6 = admin senior / co-owner  7 = propriétaire bot  $ = superadmin uniquement
// ══════════════════════════════════════════════════════════════════════════════

const levels = {

  // ── Bot owner / SuperAdmin uniquement ($) ────────────────────────────────
  'eval':          '$',
  '!eval':         '$',
  'owner':         '$',
  'reloadbuyers':  '$',
  'reloadconfig':  '$',
  'tester':        '$',
  'buyer':         '$',
  'buyerslist':    '$',
  'unbuyer':       '$',
  'hown':          '$',
  'superadmin':    '$',
  'sadmin':        '$',
  'sa':            '$',

  // ── Niveau 7 — Propriétaire du bot ───────────────────────────────────────
  'vn1':           7,
  'statut':        7,
  'status':        7,
  'rotator':       7,
  'statusrotator': 7,
  'botconfig':     7,
  'backuprestore': 7,
  'custom':        7,
  'blrank':        7,
  'backup':        7,
  'setpp':         7,
  'setradio':      7,
  'theme':         7,
  'mybots':        7,
  'bot_blacklist': 7,
  'command_manage':7,
  'owners':        7,
  'perm_buyer':    7,
  'system':        7,

  // ── Niveau 6 — Admin senior / Co-owner ───────────────────────────────────
  'prefix':        6,
  'perm':          6,
  'ghost':         6,
  'bl':            6,
  'blacklist':     6,
  'globalban':     6,
  'gban':          6,
  'unbl':          6,
  'unblacklist':   6,
  'ungban':        6,
  'unglobalban':   6,
  'wl':            6,
  'lockinvite':    6,
  'setrank':       6,
  'set-rank':      6,
  'rankconfig':    6,
  'setperm':       6,
  'setpermission': 6,
  'perms':         6,
  'banip':         6,
  'ipban':         6,
  'unbanip':       6,
  'ipunban':       6,
  'baniplist':     6,
  'ipbanlist':     6,
  'listbanip':     6,
  'dmall':         6,
  'addcr':         6,
  'setcr':         6,

  // ── Niveau 5 — Administrateur ────────────────────────────────────────────
  'cleanup':       5,
  'clonechannel':  5,
  'massrole':      5,
  'antiraid':      5,
  'levels':        5,
  'derank':        5,
  'rank':          5,
  'grade':         5,
  'ranger':        5,
  'addinvites':    5,
  'removeinvites': 5,
  'captcha':       5,
  'welcome':       5,
  'welcome_complete': 5,
  'boostmsg':      5,
  'boostmessage':  5,
  'boostconfig':   5,
  'style':         5,
  'settheme':      5,
  'customstyle':   5,
  'lockall':       5,
  'unlockall':     5,
  'linkchannel':   5,
  'syncsalon':     5,
  'setallsalon':   5,

  // ── Niveau 4 — Modérateur ────────────────────────────────────────────────
  'ban':           4,
  'unban':         4,
  'kick':          4,
  'mute':          4,
  'unmute':        4,
  'timeout':       4,
  'untimeout':     4,
  'warn':          4,
  'warnlist':      4,
  'clearwarns':    4,
  'warnconfig':    4,
  'warnsanction':  4,
  'autowarn':      4,
  'warnpalier':    4,
  'softban':       4,
  'unbanall':      4,
  'history':       4,
  'lock':          4,
  'unlock':        4,
  'lockdown':      4,
  'slowmode':      4,
  'nick':          4,
  'clear':         4,
  'deafen':        4,
  'undeafen':      4,
  'voicekick':     4,
  'voicemute':     4,
  'voiceunmute':   4,
  'mov':           4,
  'movall':        4,
  'swap':          4,
  'addrole':       4,
  'delrole':       4,
  'mutelist':      4,
  'banlist':       4,
  'checkalts':     4,
  'automod':       4,
  'muterole':      4,
  'rolelock':      4,
  'roleunlock':    4,
  'timelock':      4,
  'renew':         4,
  'renewall':      4,
  'addxp':         4,
  'jail':          4,
  'prison':        4,
  'emprisonner':   4,
  'unjail':        4,
  'liberer':       4,
  'unprison':      4,
  'namerole':      4,
  'rolepanel':     4,
  'rolemenu':      4,
  'autorole':      4,
  'autorank':      4,
  'raidlog':       4,
  'raidconfig':    4,
  'hideall':       4,
  'unhideall':     4,
  'hidecategory':  4,
  'unhidecategory':4,
  'masshide':      4,
  'embed':         4,
  'say':           4,
  'ticket':        4,
  'digicode':      4,
  'digi':          4,
  'confdigi':      4,
  'antibot':       4,
  'antilink':      4,
  'antispam':      4,
  'antimassmention':4,
  'counter':       4,
  'starboard':     4,
  'suggestsetup':  4,
  'tempvoc':       4,
  'limrole':       4,
  'custemoji':     4,
  'emoji':         4,
  'logs':          4,
  'vc':            4,
  'voice':         4,
  'soutien':       4,

  // ── Niveau 3 — Modérateur junior ─────────────────────────────────────────
  'giveaway':      3,
  'report':        3,
  'hide':          3,
  'unhide':        3,
  'hidetext':      3,
  'unhidetext':    3,
  'locktext':      3,
  'unlocktext':    3,
  'lockvoice':     3,
  'unlockvoice':   3,
  'close':         3,
  'sup':           3,
  'supg':          3,
  'setsop':        3,
  'rename':        3,
  'topic':         3,
  'textallsalon':  3,

  // ── Niveau 2 — OSINT / Staff accès restreint ─────────────────────────────
  'lookup':        2,
  'breach':        2,
  'geoip':         2,
  'intel':         2,
  'snusbase':      2,
  'vpncheck':      2,
  'whoisdomain':   2,
  'pastebin':      2,
  'phoneinfo':     2,
  'msgsearch':     2,
  'scraper':       2,
  'searchmsg':     2,
  'messages':      2,
  'scrapemessages':2,
  'hashlookup':    2,
  'hash':          2,
  'decrypt_hash':  2,
  'hashcheck':     2,
  'username':      2,
  'usercheck':     2,
  'namesearch':    2,
  'socialcheck':   2,
  'emailinfo':     2,
  'email':         2,
  'emailcheck':    2,
  'verifyemail':   2,
  'socialsearch':  2,
  'social':        2,
  'usernamecheck': 2,
  'urlinfo':       2,
  'url':           2,
  'urlinspect':    2,
  'urlcheck':      2,
  'dork':          2,
  'dorking':       2,
  'googledork':    2,
  'dorks':         2,
  'osint_resources':2,
  'ressources':    2,
  'osint_ressources':2,
  'osintlinks':    2,
  'osint_links':   2,
  'alladmin':      2,
  'allbotadmin':   2,
  'allbot':        2,
  'boosters':      2,

  // ── Niveau 1 — Membre avec rôle basique ──────────────────────────────────
  'honor':         1,
  'tableau':       1,
  'classement':    1,
  'hof':           1,
  'invites':       1,
  'vanity':        1,

  // ── Niveau 0 — Tout le monde (pas de permission requise) ─────────────────
  // Ces commandes n'ont pas besoin d'entrée ici car l'absence d'entrée
  // + catégorie non protégée = accès libre.
  // On les liste explicitement pour clarté et pour le +help.
  'help':          0,
  'aide':          0,
  'h':             0,
  'myhelp':        0,
  'helpall':       0,
  'ping':          0,
  'stats':         0,
  'serverinfo':    0,
  'userinfo':      0,
  'channelinfo':   0,
  'roleinfo':      0,
  'membercount':   0,
  'serverstats':   0,
  'banner':        0,
  'image':         0,
  'invite':        0,
  'shorturl':      0,
  'qrcode':        0,
  'top':           0,
  'pic':           0,
  'suggest':       0,
  'levell':        0,
  'snipe':         0,
  'leaderboard':   0,
  'profile':       0,
  'stu':           0,
  '8ball':         0,
  'coinflip':      0,
  'hug':           0,
  'kiss':          0,
  'pat':           0,
  'poll':          0,
  'roll':          0,
  'ship':          0,
  'slap':          0,
  'search':        0,
  'laws':          0,
  'diag':          0,
  'perm_list':     0,
  'archive':       0,
  'afk':           0,
  'afklist':       0,
};

module.exports = {
  levels,
  getLevelFor(name) {
    return levels[name];
  }
};
